### Problem 2

(a) Define a variable named `My.Name` in R by assigning your name as character to that variable.

In [1]:
my.name = 'Vo Huynh Quang Nguyen'

(b) Use the `is.numeric` function to check if the variable My.Name is a numeric variable. Similarly use the `is.character` function.

In [2]:
print(is.numeric(my.name))
print(is.character(my.name))

[1] FALSE
[1] TRUE


(c) Define a variable called `age` by assigning your age in whole years to this variable. 

In [3]:
age = 28

(d) What should be the output if you use the following?

`paste(“The age of”, My.Name, “is”, age)`

Run the code and see if the output make sense. Notice if the rule of coercion that we learned in class is satisfied here.

In [4]:
print(paste('The age of', my.name, 'is', age))

[1] "The age of Vo Huynh Quang Nguyen is 28"


### Problem 3

Define a variable called `num` and assign the value 5 to it. Write a line of R code to check if `num` to the power `num` is greater than 10000. Now assign 500 to `num` and find the value of `num` to the power `num`. Can you explain what you see as the output?  

In [6]:
num <- 5
print((num ** num) > 10000)

num <- 500
print((num ** num) > 10000)

[1] FALSE
[1] TRUE


### Problem 5
Use R to solve this problem. Define the matrices `C` and `D` above in R.

In [7]:
C <- matrix(c(-1,0,0,-1,8,8), nrow = 3, ncol = 2, byrow = TRUE)
print(C)
D <- matrix(c(1,2,1,2,3,0,1,0,4), nrow = 3, ncol = 3, byrow = TRUE)
print(D)

     [,1] [,2]
[1,]   -1    0
[2,]    0   -1
[3,]    8    8
     [,1] [,2] [,3]
[1,]    1    2    1
[2,]    2    3    0
[3,]    1    0    4


(i) Use R-coding to find the submatrix of `D` that contains the first 2 rows of `D` and the last two
columns of `D`.

In [8]:
print(D[1:2, 2:3])

     [,1] [,2]
[1,]    2    1
[2,]    3    0


(ii) Use R-coding to extract the diagonal of matrix `D`. Let us call that vector `vec1`. Define the first
column of matrix `C` as `vec2`. Add `vec1` and `vec2`.

In [9]:
vec1 <- (diag(D))
print(vec1)
vec2 <- C[1:3,1]
print(vec2)
print(vec1 + vec2)

[1] 1 3 4
[1] -1  0  8
[1]  0  3 12


(iv) Without printing the dimensions of the matrices, can you use R to check if `C` and `D` have
equal number of rows?

In [10]:
print(dim(C)[1] == dim(D)[1])


[1] TRUE
