In [1]:
import numpy as np
import math as m

In [2]:
M = np.array([[2, 1],
              [-3, 6]], dtype = float)
char_polys = np.poly(M)
print(char_polys)

w_M, v_M = np.linalg.eig(M)
print(v_M)

[ 1. -8. 15.]
[[-0.70710678 -0.31622777]
 [-0.70710678 -0.9486833 ]]


In [4]:
I = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]], dtype = float)
w_I, v_I = np.linalg.eig(I)
print(w_I)

[1. 1. 1.]


In [6]:
A = np.array([[1, 2],
              [0, 4]], dtype = float)
B = np.array([[1, 0],
              [0, 1]], dtype = float)
C = np.dot(A, B)
w_C, v_C = np.linalg.eig(C)
print(w_C)
print(v_C)

[1. 4.]
[[1.         0.5547002 ]
 [0.         0.83205029]]


In [8]:
P = np.array([[2, 0, 0],
              [1, 2, 1],
              [-1, 0, 1]], dtype = float)
w_P, v_P = np.linalg.eig(P)
print(w_P)
print(v_P)

[2. 1. 2.]
[[ 0.          0.          0.70710678]
 [ 1.         -0.70710678  0.        ]
 [ 0.          0.70710678 -0.70710678]]


In [ ]:
M = np.array([[3, 1, -2],
              [4, 0, 1],
              [2, 1, -1]], dtype = float)
char_polys = np.poly(M)
print(char_polys)