A system of three linear equations has the following expression in matrix notation:
$$
\mathbf{y} = \mathbf{W}\mathbf{x}
$$

with
* $\mathbf{x}$ is a column vector representing our inputs whose size is (3,1).
* $\mathbf{y}$ is a column vector representing our outputs whose size is (3,1).
* $\mathbf{W}$ is a matrix representing our coefficients whose size is (3,3).

# Experiment (with ideal characteristics)
Let $X = \begin{bmatrix} 9. \\ 15. \\ 35. \end{bmatrix}$ and $W = \begin{bmatrix} 8. & 3. & -2. \\ -4. & 7. & 5. \\ 3. & 4. & -12. \end{bmatrix}$.

In [26]:
W = [[8., 3., -2.], [-4., 7., 5.], [3., 4., -12.]]
X = [9., 15., 35.]

## Approach 1
We construct a single perceptron deep learning model with only a linear activation. No backward propagation is performed.

Once the model is implemented and mapped to the corresponding memristive deep neural network (MDNN), we feed the input vector $X$ to the corresponding memristive network.

In [27]:
import torch
import torch.nn as nn
import numpy as np
import memtorch

class Reference(nn.Module):
    def __init__(self):
        super(Reference, self).__init__()
        pass

    def forward(self, X, W):
        self.X = torch.tensor(X, requires_grad= True)
        self.W = torch.tensor(W, requires_grad= True)
        result = torch.matmul(self.W, self.X)
        return result
    
##
# Define a reference model:
#
reference_model = Reference()
reference_results = reference_model.forward(X, W)
print(reference_results)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(in_features = 3, out_features = 3, bias = False)

    def forward(self, inputs):
      input_tensor = torch.tensor(inputs, requires_grad = True)
      output_tensor = self.fc(input_tensor)
      return output_tensor
    
##
# Define a test model:
#
test_model = Net()
with torch.no_grad(): test_model.fc.weight.data = torch.tensor(W, requires_grad= True)
print(test_model.fc.weight)
test_results = test_model.forward(X)


tensor([  47.,  244., -333.], grad_fn=<MvBackward0>)
Parameter containing:
tensor([[  8.,   3.,  -2.],
        [ -4.,   7.,   5.],
        [  3.,   4., -12.]], requires_grad=True)


In [28]:
import copy
from memtorch.mn.Module import patch_model
from memtorch.map.Parameter import naive_map
from memtorch.map.Input import naive_scale

device = torch.device('cpu' if 'cpu' in memtorch.__version__ else 'cuda')

reference_memristor = memtorch.bh.memristor.VTEAM
reference_memristor_params = {"time_series_resolution": 1e-10, "r_off": 100e3, "r_on": 10e3,}
model = Net().to(device)

patched_model = patch_model(copy.deepcopy(model),
                          memristor_model=reference_memristor,
                          memristor_model_params=reference_memristor_params,
                          module_parameters_to_patch=[torch.nn.Conv1d],
                          mapping_routine=naive_map,
                          transistor=True,
                          programming_routine=None,
                          tile_shape=(3,3),
                          max_input_voltage=0.3,
                          scaling_routine=naive_scale,
                          ADC_resolution=8,
                          ADC_overflow_rate=0.,
                          quant_method='linear')

print(patched_model.fc.weight)
patched_model.forward(X)

Parameter containing:
tensor([[ 0.1813,  0.2123, -0.2646],
        [-0.3811, -0.1741, -0.0134],
        [ 0.3399,  0.4545,  0.0471]], requires_grad=True)


tensor([-4.4461, -6.5125, 11.5244], grad_fn=<SqueezeBackward4>)

## Approach 2
We construct a memristor crossbar array. 

In [29]:
import torch
import torch.nn as nn
import numpy as np
import memtorch

from memtorch.map.Parameter import naive_map
from memtorch.bh.crossbar.Crossbar import init_crossbar

class IdealMCA():
    def __init__(self, W):
        super(IdealMCA, self).__init__()
        # self.X = torch.tensor(X, requires_grad= True)
        self.W = torch.tensor(W, requires_grad= True)
        self.define_memristor_behaviours()
        self.define_crossbar()
        pass
    
    def define_memristor_behaviours(self):
        self.reference_memristor = memtorch.bh.memristor.VTEAM
        self.reference_memristor_params = {
    'time_series_resolution': 1e-6,
    'alpha_off': 1,
    'alpha_on': 3,
    'v_off': 0.5,
    'v_on': -0.53,
    'r_off': 2.5e3,#2.5e3
    'r_on': 100,#100
    'k_off': 4.03e-8,
    'k_on': -80,
    'd': 10e-9,
    'x_on': 0,
    'x_off': 10e-9
}
        pass

    def define_crossbar(self):
        self.crossbars, self.operation = init_crossbar(
            weights = self.W,
            memristor_model= self.reference_memristor,
            memristor_model_params= self.reference_memristor_params,
            transistor= True,
            mapping_routine= naive_map,
            programming_routine= None,
            tile_shape= (3,3),
            scheme= memtorch.bh.crossbar.Scheme.DoubleColumn,
        )
    
    def forward(self,X):
        self.X = torch.tensor(X, requires_grad= True)
        #self.W = torch.tensor(W, requires_grad= True)
        self.W = self.operation(self.crossbars, lambda crossbar: crossbar.conductance_matrix)
        self.results = torch.matmul(self.W, self.X)
        # print(f'Crossbar Product: {self.results}')
        return self.results 
        pass

##
# Define the crossbar
#
test_model = IdealMCA(W)
test_results = test_model.forward(X)
print(test_results)

tensor([[ 0.0936,  0.2176, -0.2904]], grad_fn=<UnsafeViewBackward0>)


The reason this produces a scaled output is that the elements of $W$ are encoded on the crossbar using conductance values which can be represented by each device, i.e., they are scaled and encoded between $1/r_{off}$ and $1/r_{on}$. In MCA, the Ohm's law is exploited to perform Vector-Matrix Multiplication, so:
* Elements of tensor $X$ are encoded as Word Line (WL) voltages.
* Elements of tensor $Y$ is given as: $I=GV$ (assuming linear I/V characteristics and that line and source resistances are negligible/select devices are used). Since encoded elements of tensor $X$ are scaled, the resulting currents, i.e., $I$, must be scaled much that they are approximately equal to the desired product, which is $GV \equiv WX$.

We can find the scalar that scales the crossbar's outputs back to the expected crossbar as follows: 

In [30]:
W = [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]
X = [[1., 1., 1.], [100., 100., 100.], [100., 100., 1.], [9., 15., 35.]]

test_model = IdealMCA(W)
reference_model = Reference()

Yhat = []
Y = []
for i in range(4):
    y = reference_model.forward(X[i], W)
    y = y.detach().numpy()
    Y.append(y)
    print(y)

    yhat = test_model.forward(X[i])
    yhat = yhat.detach().numpy()
    Yhat.append(yhat)
    print(yhat)

[1. 1. 1.]
[[0.0096 0.0096 0.0096]]
[100. 100. 100.]
[[0.96 0.96 0.96]]
[100. 100.   1.]
[[0.96   0.96   0.0096]]
[ 9. 15. 35.]
[[0.08639999 0.144      0.336     ]]


In [31]:
from memtorch.bh.nonideality.DeviceFaults import apply_cycle_variability
distribution = torch.distributions.normal.Normal

test_model_exp1 = apply_cycle_variability(test_model, distribution, r_off_kwargs={"loc":0,"scale":1}, r_on_kwargs={"loc":0,"scale":1})

c:\ProgramData\anaconda3\envs\memristor\Lib\site-packages\memtorch\bh\nonideality\DeviceFaults.py:116: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ) and arg.name is not "validate_args":
c:\ProgramData\anaconda3\envs\memristor\Lib\site-packages\memtorch\bh\nonideality\DeviceFaults.py:116: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ) and arg.name is not "validate_args":
c:\ProgramData\anaconda3\envs\memristor\Lib\site-packages\memtorch\bh\nonideality\DeviceFaults.py:116: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ) and arg.name is not "validate_args":
c:\ProgramData\anaconda3\envs\memristor\Lib\site-packages\memtorch\bh\nonideality\DeviceFaults.py:116: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ) and arg.name is not "validate_args":


AttributeError: 'IdealMCA' object has no attribute 'tile_shape'